//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventUser
    {
        public long UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserAddress { get; set; }
        public string EmailAddress { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
