//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventBooking
    {
        public long BookingId { get; set; }
        public Nullable<long> EventId { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
